package com.mycompany.myapp;

//import Views.ui_Test;
import Entities.User.User;
import Views.MainFrameView;
import Views.User.ForgotView;
import Views.User.LoginView;
import com.codename1.components.ImageViewer;
import static com.codename1.ui.CN.*;
import com.codename1.io.Log;
import com.codename1.ui.Button;
import com.codename1.ui.Container;
import com.codename1.ui.Dialog;
import com.codename1.ui.FontImage;
import com.codename1.ui.Form;
import com.codename1.ui.Image;
import com.codename1.ui.Label;
import com.codename1.ui.Toolbar;
import com.codename1.ui.events.ActionEvent;
import com.codename1.ui.layouts.BorderLayout;
import com.codename1.ui.plaf.UIManager;
import com.codename1.ui.util.Resources;
import com.codename1.ui.util.UIBuilder;
//import ui_Test;

/**
 * This file was generated by <a href="https://www.codenameone.com/">Codename One</a> for the purpose 
 * of building native mobile applications using Java.
 */
public class MyApplication {
    private static  Resources theme;    
    private static User ConnectedUser;
    public static Resources  getTheme(){return MyApplication.theme;}// Theme
    public static User getConnectedUser(){return MyApplication.ConnectedUser; }// Session owner
    public static LoginView getUiLogin() {return uiLogin;}
    public static ForgotView getUiForgot() {return uiForgot;}
    public static MainFrameView getUiMainFrame() {return uiMainFrame;}
    public static void setConnectedUser(User U) {MyApplication.ConnectedUser=U;}
    private static LoginView uiLogin;
    private static ForgotView uiForgot;
    //private ui_Test t;
    

    private Form current;
    private static MainFrameView uiMainFrame;
    
    public void init(Object context)  {  
    theme = UIManager.initFirstTheme("/theme");
    UIBuilder.registerCustomComponent("ImageViewer",ImageViewer.class);
    uiMainFrame = new MainFrameView();
    //t=new ui_Test();
    uiLogin=new LoginView();
    uiForgot= new ForgotView();
        // Pro only feature
        Log.bindCrashProtection(true);
    }
    public void start() {
       
        if(uiLogin.RenderView()!= null){
            uiLogin.RenderView().show();
            return;
        }
    }
    public void stop() {
        current = getCurrentForm();
        if(current instanceof Dialog) {
            ((Dialog)current).dispose();
            current = getCurrentForm();
        }
    }
    public void destroy() {
    }
}
